### ISSUE TITLE
kernel modules on R020

### ISSUE THREAD

**Issue by a520ass** [0neday/OptiXstarHS8145X6#1]
Is there any progress in compiling kernel modules on R020, and I'm trying to compile mtd_rw.ko, using insmod mtd_rw.ko does not have any log output

**Comment by 0neday** [comment]
> using insmod mtd_rw.ko does not have any log output

use command `dmesg` to show.

check my question,  [PLTs error , not work now](https://v2ex.com/t/821614). If you fix PLTs error, please sharing with me, thank you.
